### ISSUE TITLE
ParseError: "constraint 检查错误 字段`ding.ding.tree`不存在

### ISSUE THREAD

**Issue by jili3221058** [gilbert-yuan/odoo_dingding#2]
File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1079, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "constraint 检查错误
字段ding.ding.tree不存在
错误的上下文:
[view_id: 915, xml_id: n/a, model: ding.ding, parent_id: n/a]
None" while parsing /usr/lib/python2.7/dist-packages/odoo/addons/dingding/ding_model.xml:4, near
<record id="ding_ding_tree" model="ir.ui.view">
            <field name="name">ding.ding.tree</field>
            <field name="model">ding.ding</field>
            <field name="arch" type="xml">
                <tree string="&#38025;&#38025;">
                    <field name="name"/>
                    <field name="corpid"/>
                    <field name="corpsecret"/>
                </tree>
            </field>
        </record>

**Comment by jili3221058** [comment]
需要额外的配置 信息吗？

**Comment by gilbert-yuan** [comment]
不好意思。。。没关注issue

**Comment by gilbert-yuan** [comment]
现在应该好用了。 
![4672b0f4-f50c-482e-a967-66fa4d3f756b](https://user-images.githubusercontent.com/13111533/38846534-718ad4ec-422f-11e8-8cc6-a38663c7e691.png)

**Comment by gilbert-yuan** [comment]
![4672b0f4-f50c-482e-a967-66fa4d3f756b](https://user-images.githubusercontent.com/13111533/38846745-9bc86cd2-4230-11e8-819c-8b38c111d106.png)现在应该好用了 不过不要用我的账号进行操作。因为密码重置了。

**Comment by zlc000190** [comment]
厄， 用我自己的钉钉账户，还是和楼上哪哥们一样的错误啊

**Comment by gilbert-yuan** [comment]
这个问题最新代码已经修复了。。不知道你的啥问题。。

**Comment by gilbert-yuan** [comment]
这是odoo10上的

**Comment by zlc000190** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 895, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 883, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 411, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 796, in parse
    self.parse(rec, mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1236, in _update
    record = record.create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 362, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3855, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 1046, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 380, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3568, in write
    self._write(old_vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3732, in _write
    self._validate_fields(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1081, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "constraint \u68c0\u67e5\u9519\u8bef

\u6ca1\u6709\u627e\u5230\u6a21\u578b: ding.ding

\u9519\u8bef\u7684\u4e0a\u4e0b\u6587:
\u89c6\u56fe `ding.ding.tree`
[view_id: 982, xml_id: n/a, model: ding.ding, parent_id: n/a]
None" while parsing /usr/lib/python2.7/dist-packages/odoo/addons/dingding/ding_model.xml:4, near
<record id="ding_ding_tree" model="ir.ui.view">
            <field name="name">ding.ding.tree</field>
            <field name="model">ding.ding</field>
            <field name="arch" type="xml">
                <tree string="&#38025;&#38025;">
                    <field name="name"/>
                    <field name="corpid"/>
                    <field name="corpsecret"/>
                </tree>
            </field>
        </record>
